name: Clipboard
version: 0.03
abstract: Cliboard - Copy and Paste with any OS
author: Ryan King <rking@panoptic.com
license: perl
distribution_type: module
requires:
  Spiffy: 0
  IO::All: 0
no_index:
  directory:
    - inc
generated_by: Module::Install version 0.36
